kind: ConfigMap
apiVersion: v1
metadata:
  name: vaultconfigmap
  namespace: red
data:
  # Configuration values can be set as key-value properties
  # Or set as complete file contents (even JSON!)
  vault.hcl: |+
    storage "file" {
      path = "/tmp"
    }

    disable_mlock = true

    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = true
    }

  initscript_vault.sh: |+
    #!/bin/sh
    sleep 50
    apt-get update
    apt-get install -y curl
    vault operator init -key-shares 1 -key-threshold 1 > temp.txt
    UNSEALKEY=`grep 'Unseal Key 1:' temp.txt | awk '{print $NF}'`
    INITKEY=`grep 'Initial Root Token:' temp.txt | awk '{print $NF}'`
    vault operator unseal ${UNSEALKEY}
    export VAULT_TOKEN=${INITKEY}

    # echo details (for debugging)
    echo ${UNSEALKEY}
    echo ${INITKEY}

    # Setup SSH CA
    vault secrets enable ssh
    vault write ssh/config/ca generate_signing_key=true
    # Setup CA access and ttl
    vault write ssh/roles/default -<<"EOH"
    {
      "allow_user_certificates": true,
      "allowed_users": "*",
      "default_extensions": [
        {
          "permit-pty": ""
        }
      ],
      "key_type": "ca",
      "default_user": "ubuntu",
      "ttl": "30m0s"
    }
    EOH

    sleep 1000
