apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: shreyaspace
  labels :
    app : vaultapp
spec:

  replicas: 1
  selector:
    matchLabels:
      app: vaultapp
  template:
    metadata:
      labels:
        app: vaultapp
    spec:
      containers:
      - name: vaultapp
        image: registry.hub.docker.com/library/vault:1.1.3
        imagePullPolicy: Always
        volumeMounts:
          - name: vaultconfigmap-volume
            mountPath: /vault/home
        command: ['vault']
        args: ['server', '-config', '/vault/home/vault.hcl']
        ports:
        - containerPort: 8200
          name: vault-port
          protocol: TCP
          #restartPolicy: Always
      - image: ubuntu:18.04
        name: vaultuser
        volumeMounts:
          - name: mystorage
            mountPath: /vault
        command: ['/vault/init_vault.sh']
      volumes:
        - name: mystorage
          hostPath:
            path: /Users/shreya.chatterjee/Documents/solid-telegram/kubernetes/redteam/RedTeam
            type: Directory

          # `name` here must match the name
          # specified in the volume mount
        - name: vaultconfigmap-volume
            # Populate the volume with config map data
          configMap:
              # `name` here must match the name
              # specified in the ConfigMap's YAML
              name: vaultconfigmap
        #env:
        #  VAULT_ADDR: 'http://vault:8200'
