apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  #namespace: shreyaspace
  labels :
    app : vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vaultapp
        image: vault:1.2.3
        #env:
        #  - name: VAULT_ADDR
        #    value: 'http://10.101.133.80:8200'
        volumeMounts:
          - name: vault-cm-storage
            mountPath: /vaultcm

        command: ['vault']
        args: ['server', '-config', '/vaultcm/vault.hcl']
        #ports:
        #- containerPort: 8200
        #  name: vault-port
        #  protocol: TCP
      - image: vault:1.2.3
        name: vaultuser
        env:
          #- name: VAULT_ADDR
          #  value: 'http://vaultapp:8200'
          #- name: VAULT_ADDR
          #  valueFrom:
          #    configMapKeyRef:
          #      name: vault
          #      key: vault_addr
        volumeMounts:
          - name: mystorage
            mountPath: /vault
          #- name: vault-cm-storage
          #  mountPath: /vault-cm-storage
        command: ['/vault/vault_init.sh']
      volumes:
        - name: vault-cm-storage
          configMap:
            name: vault-configmap
        - name: mystorage
          hostPath:
            path: /Users/eric.echter/github/RedTeam/ericechter/red
            type: Directory
